Filter and search
ABI-Software/12-labours-api pull request #11
Opened 2022-11-30 21:56 UTC by jyu748

This pull request contains:
1. New filter-related support api, reduces the loading time.
2. Irods search-related api, provide keywords search feature. The result will be ordered by relevance.
3. Separated graphql apis based on different use.
4. Updated test cases with latest apis.

2022-12-08 03:52 UTC, alan-wu requested changes
It looks good in general, I need to test the IRODS search but I am not able to do so at this moment. Thanks.

2022-12-08 03:52 UTC, alan-wu commented on app/filter.py
> +    "MAPPED_MIME_TYPES2": {
Do we need this one?

2022-12-08 03:52 UTC, alan-wu commented on app/filter.py
> +    "MAPPED_FUNDING2": {
Can we replace this one with species?

2022-12-08 03:52 UTC, alan-wu commented on app/main.py
> +    return f.generate_dataset_list(query_result[item.node])
Do these two routes do completely different things?

Probably can find a better name for the second route.

2022-12-08 03:52 UTC, alan-wu commented on app/main.py
> +@ app.post("/filter/argument")
Would filter/dataset be a better route for this?
The function can be called get_filtered_datasets?

2022-12-08 03:52 UTC, alan-wu commented on tests/test_api.py
> +    assert response.json()[
Assign response.json() to a variable then access its element will be better for readability.

2022-12-08 03:52 UTC, alan-wu commented on app/main.py
> +async def search_content(item: SearchItem):
Please provide an example on the post request data. I would like to test it.

2022-12-08 03:52 UTC, alan-wu commented on app/main.py
> +async def search_content(item: SearchItem):
If it is an input string only, changing it to GET will be better,

2022-12-08 20:20 UTC, david-jianwei-yu commented on app/filter.py
> +    "MAPPED_FUNDING2": {
Sure, will do that now. It's just a test filter.

2022-12-11 23:07 UTC, alan-wu approved these changes

2022-12-11 23:07 UTC, merged