Dev
ABI-Software/12-labours-api pull request #9
Opened 2022-09-12 04:27 UTC by jyu748

2022-09-19 23:37 UTC, alan-wu requested changes
I would like to revisit some of the codes in the future but it looks pretty good so far. Thanks.
I think some of the codes in the generate_****_filter methods can be reused.

2022-09-19 23:37 UTC, alan-wu commented on app/filter.py
> +    def generate_mimetypes_filter_data(self, data):
Part of the generate_mimetypes_filter_data, generate_anatomy_filter_data and generate_species_filter_data are quite similar.  You can probably merge some of them into a method.

2022-09-20 02:10 UTC, jyu748 commented on app/filter.py
> +    def generate_mimetypes_filter_data(self, data):
I have made some updates for these three functions. And think of a way to re-generate the gen3 token when 401 happens, but still needs some tests.

2022-09-21 01:12 UTC, alan-wu approved these changes
Looking good.

2022-09-21 01:12 UTC, merged